Presentation/CryptoManager.WebApplication/Controllers/HomeController.cs
using CryptoManager.Infrastructure.Hubs;
using CryptoManager.Infrastructure.Responses.Bitfinex;
using CryptoManager.Infrastructure.Services.Bitfinex.Interfaces;
using CryptoManager.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Diagnostics;

namespace CryptoManager.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRestConnector _restConnector;
        private readonly IWebsocketConnector _websocketConnector;
        private readonly IHubContext<TradeHub> _hubContext;

        public HomeController(IRestConnector restConnector, IWebsocketConnector websocketConnector, IHubContext<TradeHub> hubContext)
        {
            _restConnector = restConnector;
            _websocketConnector = websocketConnector;
            _hubContext = hubContext;
        }

        public async Task<IActionResult> Index()
        {
            await _websocketConnector.ConnectAsync();
            _websocketConnector.NewBuyTrade += async trade =>
            {
                await _hubContext.Clients.All.SendAsync("ReceiveTrade", trade.Id, trade.Pair, trade.Side, trade.Price, trade.Amount, trade.Time);
            };

            _websocketConnector.NewSellTrade += async trade =>
            {
                await _hubContext.Clients.All.SendAsync("ReceiveTrade", trade.Id, trade.Pair, trade.Side, trade.Price, trade.Amount, trade.Time);
            };

            _websocketConnector.CandleSeriesProcessing += async candle =>
            {
                await _hubContext.Clients.All.SendAsync("ReceiveCandle",
                    candle.Pair,
                    candle.OpenPrice,
                    candle.ClosePrice,
                    candle.HighPrice,
                    candle.LowPrice,
                    candle.TotalVolume,
                    candle.TotalPrice,
                    candle.OpenTime.ToUnixTimeMilliseconds());
            };

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCurrencyPairs()
        {
            CurrencyResponse currency = await _restConnector.GetCurrencyAsync();

            CurrencyModel model = new CurrencyModel()
            {
                Pairs = currency.Pairs,
            };
            return Json(new { pairs = model.Pairs });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/CryptoManager.WebApplication/Controllers/RestController.cs
using CryptoManager.Infrastructure.Responses.Bitfinex;
using CryptoManager.Infrastructure.Services.Bitfinex.Interfaces;
using CryptoManager.WebApplication.Models;
using CryptoManager.WebApplication.Requests;
using Microsoft.AspNetCore.Mvc;

namespace CryptoManager.WebApplication.Controllers
{
    [Route("[controller]")]
    public class RestController : Controller
    {
        private readonly IRestConnector _restConnector;

        public RestController(IRestConnector restConnector) => _restConnector = restConnector;

        [HttpGet("Manage")]
        public IActionResult Manage()
        {
            return View();
        }

        [HttpPost("TickerTableGeneration")]
        public async Task<IActionResult> TickerTableGeneration([FromBody] TickerRequest request)
        {
            TickerResponce ticker = await _restConnector.GetTickerAsync(request.Pair);

            TickerModel model = new TickerModel()
            {
                Pair = ticker.Pair,
                AskPrice = ticker.AskPrice,
                AskSize = ticker.AskSize,
                BidPrice = ticker.BidPrice,
                BidSize = ticker.BidSize,
                DailyChange = ticker.DailyChange,
                LastPrice = ticker.LastPrice,
                DailyChangeRelative = ticker.DailyChangeRelative * 100,
                High = ticker.High,
                Low = ticker.Low,
                Volume = ticker.Volume
            };

            return Json(new
            {
                data = model
            });
        }

        [HttpPost("CandlesTableGeneration")]
        public async Task<IActionResult> CandlesTableGeneration([FromBody] CandlesRequest request)
        {
            IEnumerable<CandleResponse> candles = await _restConnector.GetCandleSeriesAsync(request.Pair, request.Period, request.From, request.To, request.Count);

            List<CandleModel> models = new List<CandleModel>();
            foreach (CandleResponse candle in candles)
            {
                CandleModel model = new CandleModel()
                {
                    ClosePrice = candle.ClosePrice,
                    HighPrice = candle.HighPrice,
                    LowPrice = candle.LowPrice,
                    OpenPrice = candle.OpenPrice,
                    OpenTime = candle.OpenTime,
                    Pair = candle.Pair,
                    TotalPrice = candle.TotalPrice,
                    TotalVolume = candle.TotalVolume
                };
                models.Add(model);
            }
            return Json(new
            {
                data = models
            });
        }

        [HttpPost("TradesTableGeneration")]
        public async Task<IActionResult> TradesTableGeneration([FromBody] TradesRequest request)
        {
            IEnumerable<TradeResponse> trades = await _restConnector.GetNewTradesAsync(request.Pair, request.MaxCount);

            List<TradeModel> models = new List<TradeModel>();
            foreach (TradeResponse trade in trades)
            {
                TradeModel model = new TradeModel()
                {
                    Id = trade.Id,
                    Amount = trade.Amount,
                    Pair = trade.Pair,
                    Price = trade.Price,
                    Side = trade.Side,
                    Time = trade.Time,
                };
                models.Add(model);
            }
            return Json(new
            {
                data = models
            });
        }
    }
}

Presentation/CryptoManager.WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body>
    <header class="d-flex align-items-center justify-content-between p-3 border-bottom">
        <a href="@Url.Action("Manage", "Rest")" class="btn btn-primary">Get More Info</a>

        <button class="btn btn-primary" id="modal-btn" data-bs-toggle="modal" data-bs-target="#tableModal">Connection Bitfinex</button>
    </header>
    <main class="container py-4">
        <div id="mainTableContainer"></div>
    </main>

    <div class="modal fade" id="tableModal" tabindex="-1" aria-labelledby="tableModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tableModalLabel">Select the options you need</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="tableForm">
                        <div class="mb-3">
                            <label for="operationType" class="form-label">Operation selection</label>
                            <select class="form-select" id="operationType" required>
                                <option value="trades">Trades</option>
                                <option value="candles">Candles</option>
                            </select>
                        </div>

                        <div id="dynamicFields"></div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="submit" form="tableForm" id="subscribe" class="btn btn-success">Subscribe</button>
                    <button type="submit" form="tableForm" id="unsubscribe" class="btn btn-danger">Unsubscribe</button>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    <script src="~/js/index.js" asp-append-version="true"></script>
}